spring:
  main:
    web-application-type: none
    banner-mode: off
  ai:
    mcp:
      server:
        name: sql-forge-mcp-server
        version: 0.0.1

logging:
  pattern:
    console:
  file:
    name: ./mcp/sql-forge-mcp-server.log

sql-forge:
  api:
    url: http://localhost:8081
