spring:
  main:
    web-application-type: servlet
  datasource:
    url: jdbc:h2:file:./.local/datasource/db;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    username: sa
    password: 123456
  flyway:
    validate-on-migrate: false
  h2:
    console:
      enabled: true
  ai:
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen3.6-plus
          multi_model: true
          enable_thinking: true
      embedding:
        options:
          model: text-embedding-v2
    mcp:
      client:
        stdio:
          servers-configuration: classpath:mcp-servers.json
    loom:
      agent:
        mcps:
          - name: spring-ai-mcp-client - bing-search
            title: 必应搜索
            description: 一个集成了微软必应搜索API的模型上下文协议服务
            default-selected: true
          - name: spring-ai-mcp-client - @tokenizin-agency/mcp-npx-fetch
            title: 网页内容抓取
            description: 一个强大的MCP服务器,可以轻松地将网页内容抓取并转换为各种格式(HTML、JSON、Markdown、纯文本)
            default-selected: true
            tools:
              - name: fetch_html
                description: 获取网页内容，并以 HTML 格式返回
              - name: fetch_markdown
                description: 取网页内容，并以 Markdown 格式返回
              - name: fetch_txt
                description: 取网页内容，并以纯文本格式返回（不含 HTML）
              - name: fetch_json
                description: 从指定 URL 获取 JSON 文件
          - name: spring-ai-mcp-client - sequential-thinking
            title: 顺序思维
            description: 一种MCP服务器实现，提供动态且反射性的解决问题的工具
            tools:
              - name: sequentialthinking
                description: 本工具通过可适应与演进的灵活思维流程，协助对问题进行深入分析
          - name: spring-ai-mcp-client - memory
            title: 记忆
            description: 使用本地知识图谱实现持久化记忆
            tools:
              - name: create_entities
                description: 在知识图谱中创建多个新实体
              - name: create_relations
                description: 在知识图谱的实体之间创建多个新关系
              - name: add_observations
                description: 向知识图谱中现有实体添加新的观察信息
              - name: delete_entities
                description: 从知识图谱中删除多个实体及其关联的关系
              - name: delete_observations
                description: 从知识图谱的实体中删除特定的观察信息
              - name: delete_relations
                description: 从知识图谱中删除多个关系
              - name: read_graph
                description: 读取整个知识图谱
              - name: search_nodes
                description: 基于查询在知识图谱中搜索节点
              - name: open_nodes
                description: 通过名称打开知识图谱中的特定节点
          - name: spring-ai-mcp-client - cn-weather-mcp
            title: 中国天气
            description: 自研中国城市实时天气服务
          - name: spring-ai-mcp-client - http-client-mcp
            title: HTTP 客户端
            description: HTTP客户端MCP服务，提供通用HTTP请求功能
          - name: spring-ai-mcp-client - playwright
            title: Playwright
            description: 通过结构化可访问性快照与网页交互
          - name: spring-ai-mcp-client - chrome-devtools
            title: Chrome DevTools
            description: 控制和检查Chrome浏览器，实现自动化操作和调试
          - name: spring-ai-mcp-client - sql-forge-mcp
            title: SQL工坊
          - name: spring-ai-mcp-client - mcp-server-chart
            title: 图表
        skills:
          - name: 查询订单系统数据库
            description: 订单系统，包含系统表：用户、角色、字典等，业务表：商品、订单、支付记录、用户地址、库存、订单物流、商品分类、商品评价等
            content: classpath:skills/nl2sql.st
          - name: 创建订单系统页面
            description: 根据需要自动生成百度Amis低代码平台CRUD单表维护界面的JSON配置
            content: classpath:skills/web.st

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org:
      springframework:
        ai: DEBUG